### ISSUE TITLE
Multicharacter scripts

### ISSUE THREAD

**Issue by MushyMushroom1245** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#252]
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

Yo im having a problem with multicharacter script. Not sure if you used them or not but when ever a normal note is pressed the multicharacter script character moves. My friend Palk is also having this problem but only with hold notes. I tried downgrading to 1.19 and it works. Is there maybe a setting i have to turn on/off for them to work.
also sorry if you cant understand its hard for me to explain stuff

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment]
what multicharacter scripts are you talking about? the ones i used do work

**Comment by MushyMushroom1245** [comment]
> what multicharacter scripts are you talking about? the ones i used do work

Im talking about Capps Multicharacter script

**Comment by JordanSantiagoYT** [comment]
i don't use that multicharacter script

**Comment by JordanSantiagoYT** [comment]
and i don't really have that script so there's not much i can do 🤷‍♂️

**Comment by MushyMushroom1245** [comment]
i do kinda have a fix for it so its not so bad

**Comment by JordanSantiagoYT** [comment]
still i do need the script, so i can fix it

**Comment by MushyMushroom1245** [comment]
oh yeah here https://drive.google.com/drive/folders/1_2Y-7KvxsMtQAAzsnTfTn0_B8yB0x3Ni

**Comment by JordanSantiagoYT** [comment]
does it not work on both sides or does it work on just one

**Comment by MushyMushroom1245** [comment]
the problem is on both sides yeah. 
depending on what the "playableCharacter"  line is set to (false = dad/true = bf)

**Comment by JordanSantiagoYT** [comment]
try the latest commit, i just fixed a problem where opponent note hits called goodNoteHit instead of opponentNoteHit

**Comment by MushyMushroom1245** [comment]
Im still having the problem
Im having the problem that my friend is having now where they move on hold notes

**Comment by JordanSantiagoYT** [comment]
> Im still having the problem Im having the problem that my friend is having now where they move on hold notes

I edited the lua script so that it triggers a debugPrint every time it's supposed to trigger. It doesn't print after I changed charNote to smth other than ''.

Did you check if charNote is set to smth other than ''?

**Comment by moxie-coder** [comment]
closing due to inactivity and no response

**Comment by JordanSantiagoYT** [comment]
@MushyMushroom1245 ermm ive decided to use the script myself and it doesnt seem like im getting that issue

https://github.com/user-attachments/assets/84b5fe01-4464-4e6e-b641-8b37132d63da

**Comment by JordanSantiagoYT** [comment]
IVE FOUND THE ISSUE WITH YOUR MULTICHARACTER SCRIPTS NOT WORKING IN NEWER VERSIONS

it's because your version of the multicharacter script is outdated. newer versions of the script have it fixed, the creator also literally pointed out that issue. if you don't want to update the anyway, go into your multicharacter script and delete ALL mentions of "name_of_notetype2" as otherwise it'll either hit every note (or in the case of newer versions of jse, trigger the animation when a sustain note is hit)
